openapi: "3.0.0"
info: 
  title: Ecommerce Backend API v1
  description: "CRUD Handling"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /items/:
    # get:
    #   operationId: "api.v1.endpoints.items.ItemsView.get"
    #   description: "Get all items filtered"

    #   tags:
    #     - "Items"
        
    #   responses:
    #     "200":
    #       description: Return list of items
          
    #     "400":
    #       description: "Bad Request, Invalid input data"
    
    post:
      operationId: api.v1.endpoints.items.ItemsView.post
      description: "Create Item in database"

      tags:
        - "Items"
      
      requestBody:
        description: "Details of item to be created"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item_name: 
                  type: string
                  nullable: false
                price:
                  type: number
                  nullable: false
                description:
                    type: string 
                    nullable: true 
    
      responses:
            "201":
              description: Record Created
            "400": 
              description: "Bad Request: Invalid Input Data"

  /users/:
    post:
      operationId: api.v1.endpoints.users.UsersView.post
      description: "Create a user in database"

      tags:
        - "Users"
      
      requestBody:
        description: "Details of user to be created"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  nullable: false
                email:
                  type: string
                  nullable: false
    
      responses:
            "201":
              description: Record Created
            "400": 
              description: "Bad Request: Invalid Input Data"

  /cart/:
    post:
      operationId: api.v1.endpoints.cart.CartView.post
      description: "Create cart record in database"  

      tags:
        - "Cart"  
      
      requestBody:
          description: "Details of cart to be created"
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  item_id: 
                    type: integer
                    nullable: false
                  user_id:
                    type: integer
                    nullable: false
      
      responses:
            "201":
              description: Record Created
            "400": 
              description: "Bad Request: Invalid Input Data"
  
  /orders/:
    get: #Orders
        operationId: api.v1.endpoints.orders.OrdersView.get
        description: "Get all orders"

        tags:
          - Orders

        responses: 
          "200": 
            description: Returns list of order Config
            # schema: 
            #   type: string
          "400": 
            description: "Bad Request: Invalid Input Data"
    post:
      operationId: api.v1.endpoints.orders.OrdersView.post
      description: "Create order record in database"  

      tags:
        - "Order"  
      
      requestBody:
          description: "Details of order to be created"
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  item_id: 
                    type: integer
                    nullable: true
                  user_id:
                    type: integer
                    nullable: true
                  cart_id:
                    type: integer
                    nullable: true
      
      responses:
            "201":
              description: Record Created
            "400": 
              description: "Bad Request: Invalid Input Data"
  
  /discount/:
    get: #Orders
        operationId: api.v1.endpoints.discount.DiscountView.get
        description: "Get all Discount"

        tags:
          - Discount

        responses: 
          "200": 
            description: Returns list of Discount Config
            # schema: 
            #   type: string
          "400": 
            description: "Bad Request: Invalid Input Data"
     